package POJO;
// Generated 07/05/2015 20:45:22 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Registro generated by hbm2java
 */
public class Registro  implements java.io.Serializable {


     private Integer registroCodigo;
     private Ocorrencia ocorrencia;
     private Sensor sensor;
     private Date registroMomento;

    public Registro() {
    }

	
    public Registro(Date registroMomento) {
        this.registroMomento = registroMomento;
    }
    public Registro(Ocorrencia ocorrencia, Sensor sensor, Date registroMomento) {
       this.ocorrencia = ocorrencia;
       this.sensor = sensor;
       this.registroMomento = registroMomento;
    }
   
    public Integer getRegistroCodigo() {
        return this.registroCodigo;
    }
    
    public void setRegistroCodigo(Integer registroCodigo) {
        this.registroCodigo = registroCodigo;
    }
    public Ocorrencia getOcorrencia() {
        return this.ocorrencia;
    }
    
    public void setOcorrencia(Ocorrencia ocorrencia) {
        this.ocorrencia = ocorrencia;
    }
    public Sensor getSensor() {
        return this.sensor;
    }
    
    public void setSensor(Sensor sensor) {
        this.sensor = sensor;
    }
    public Date getRegistroMomento() {
        return this.registroMomento;
    }
    
    public void setRegistroMomento(Date registroMomento) {
        this.registroMomento = registroMomento;
    }




}


