package POJO;
// Generated 17/02/2015 16:40:52 by Hibernate Tools 4.3.1



/**
 * Sensor generated by hbm2java
 */
public class Sensor  implements java.io.Serializable {


     private int sensorCodigo;
     private Logradouro logradouro;
     private String sensorLongitude;
     private String sensorLatitude;

    public Sensor() {
    }

	
    public Sensor(int sensorCodigo) {
        this.sensorCodigo = sensorCodigo;
    }
    public Sensor(int sensorCodigo, Logradouro logradouro, String sensorLongitude, String sensorLatitude) {
       this.sensorCodigo = sensorCodigo;
       this.logradouro = logradouro;
       this.sensorLongitude = sensorLongitude;
       this.sensorLatitude = sensorLatitude;
    }
   
    public int getSensorCodigo() {
        return this.sensorCodigo;
    }
    
    public void setSensorCodigo(int sensorCodigo) {
        this.sensorCodigo = sensorCodigo;
    }
    public Logradouro getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(Logradouro logradouro) {
        this.logradouro = logradouro;
    }
    public String getSensorLongitude() {
        return this.sensorLongitude;
    }
    
    public void setSensorLongitude(String sensorLongitude) {
        this.sensorLongitude = sensorLongitude;
    }
    public String getSensorLatitude() {
        return this.sensorLatitude;
    }
    
    public void setSensorLatitude(String sensorLatitude) {
        this.sensorLatitude = sensorLatitude;
    }




}


