package POJO;
// Generated 01/04/2015 21:00:11 by Hibernate Tools 4.3.1



/**
 * Sensor generated by hbm2java
 */
public class Sensor  implements java.io.Serializable {


     private Integer sensorCodigo;
     private Logradouro logradouro;
     private String sensorLongitude;
     private String sensorLatitude;

    public Sensor() {
    }

    public Sensor(Logradouro logradouro, String sensorLongitude, String sensorLatitude) {
       this.logradouro = logradouro;
       this.sensorLongitude = sensorLongitude;
       this.sensorLatitude = sensorLatitude;
    }
   
    public Integer getSensorCodigo() {
        return this.sensorCodigo;
    }
    
    public void setSensorCodigo(Integer sensorCodigo) {
        this.sensorCodigo = sensorCodigo;
    }
    public Logradouro getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(Logradouro logradouro) {
        this.logradouro = logradouro;
    }
    public String getSensorLongitude() {
        return this.sensorLongitude;
    }
    
    public void setSensorLongitude(String sensorLongitude) {
        this.sensorLongitude = sensorLongitude;
    }
    public String getSensorLatitude() {
        return this.sensorLatitude;
    }
    
    public void setSensorLatitude(String sensorLatitude) {
        this.sensorLatitude = sensorLatitude;
    }




}


