package POJO;
// Generated 16/02/2015 18:08:10 by Hibernate Tools 4.3.1



/**
 * Tag generated by hbm2java
 */
public class Tag  implements java.io.Serializable {


     private int tagCodigo;
     private Veiculo veiculo;
     private String tagId;

    public Tag() {
    }

	
    public Tag(int tagCodigo) {
        this.tagCodigo = tagCodigo;
    }
    public Tag(int tagCodigo, Veiculo veiculo, String tagId) {
       this.tagCodigo = tagCodigo;
       this.veiculo = veiculo;
       this.tagId = tagId;
    }
   
    public int getTagCodigo() {
        return this.tagCodigo;
    }
    
    public void setTagCodigo(int tagCodigo) {
        this.tagCodigo = tagCodigo;
    }
    public Veiculo getVeiculo() {
        return this.veiculo;
    }
    
    public void setVeiculo(Veiculo veiculo) {
        this.veiculo = veiculo;
    }
    public String getTagId() {
        return this.tagId;
    }
    
    public void setTagId(String tagId) {
        this.tagId = tagId;
    }




}


