package POJO;
// Generated 09/04/2015 21:22:21 by Hibernate Tools 4.3.1



/**
 * Tag generated by hbm2java
 */
public class Tag  implements java.io.Serializable {


     private Integer tagCodigo;
     private Veiculo veiculo;
     private String tagId;

    public Tag() {
    }

    public Tag(Veiculo veiculo, String tagId) {
       this.veiculo = veiculo;
       this.tagId = tagId;
    }
   
    public Integer getTagCodigo() {
        return this.tagCodigo;
    }
    
    public void setTagCodigo(Integer tagCodigo) {
        this.tagCodigo = tagCodigo;
    }
    public Veiculo getVeiculo() {
        return this.veiculo;
    }
    
    public void setVeiculo(Veiculo veiculo) {
        this.veiculo = veiculo;
    }
    public String getTagId() {
        return this.tagId;
    }
    
    public void setTagId(String tagId) {
        this.tagId = tagId;
    }




}


