package POJO;
// Generated 07/05/2015 20:45:22 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer usuarioCodigo;
     private String usuarioLogin;
     private String usuarioSenha;

    public Usuario() {
    }

    public Usuario(String usuarioLogin, String usuarioSenha) {
       this.usuarioLogin = usuarioLogin;
       this.usuarioSenha = usuarioSenha;
    }
   
    public Integer getUsuarioCodigo() {
        return this.usuarioCodigo;
    }
    
    public void setUsuarioCodigo(Integer usuarioCodigo) {
        this.usuarioCodigo = usuarioCodigo;
    }
    public String getUsuarioLogin() {
        return this.usuarioLogin;
    }
    
    public void setUsuarioLogin(String usuarioLogin) {
        this.usuarioLogin = usuarioLogin;
    }
    public String getUsuarioSenha() {
        return this.usuarioSenha;
    }
    
    public void setUsuarioSenha(String usuarioSenha) {
        this.usuarioSenha = usuarioSenha;
    }




}


