package POJO;
// Generated 18/04/2015 23:57:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Veiculo generated by hbm2java
 */
public class Veiculo  implements java.io.Serializable {


     private Integer veiculoCodigo;
     private Condutor condutor;
     private Modelo modelo;
     private String veiculoPlaca;
     private String veiculoCor;
     private Integer veiculoAno;
     private Set tags = new HashSet(0);
     private Set ocorrencias = new HashSet(0);

    public Veiculo() {
    }

    public Veiculo(Condutor condutor, Modelo modelo, String veiculoPlaca, String veiculoCor, Integer veiculoAno, Set tags, Set ocorrencias) {
       this.condutor = condutor;
       this.modelo = modelo;
       this.veiculoPlaca = veiculoPlaca;
       this.veiculoCor = veiculoCor;
       this.veiculoAno = veiculoAno;
       this.tags = tags;
       this.ocorrencias = ocorrencias;
    }
   
    public Integer getVeiculoCodigo() {
        return this.veiculoCodigo;
    }
    
    public void setVeiculoCodigo(Integer veiculoCodigo) {
        this.veiculoCodigo = veiculoCodigo;
    }
    public Condutor getCondutor() {
        return this.condutor;
    }
    
    public void setCondutor(Condutor condutor) {
        this.condutor = condutor;
    }
    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }
    public String getVeiculoPlaca() {
        return this.veiculoPlaca;
    }
    
    public void setVeiculoPlaca(String veiculoPlaca) {
        this.veiculoPlaca = veiculoPlaca;
    }
    public String getVeiculoCor() {
        return this.veiculoCor;
    }
    
    public void setVeiculoCor(String veiculoCor) {
        this.veiculoCor = veiculoCor;
    }
    public Integer getVeiculoAno() {
        return this.veiculoAno;
    }
    
    public void setVeiculoAno(Integer veiculoAno) {
        this.veiculoAno = veiculoAno;
    }
    public Set getTags() {
        return this.tags;
    }
    
    public void setTags(Set tags) {
        this.tags = tags;
    }
    public Set getOcorrencias() {
        return this.ocorrencias;
    }
    
    public void setOcorrencias(Set ocorrencias) {
        this.ocorrencias = ocorrencias;
    }




}


