package POJO;
// Generated 17/02/2015 16:40:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Veiculo generated by hbm2java
 */
public class Veiculo  implements java.io.Serializable {


     private int veiculoCodigo;
     private Condutor condutor;
     private Modelo modelo;
     private String veiculoStatus;
     private String veiculoPlaca;
     private String veiculoCor;
     private Integer veiculoAno;
     private Set tags = new HashSet(0);

    public Veiculo() {
    }

	
    public Veiculo(int veiculoCodigo) {
        this.veiculoCodigo = veiculoCodigo;
    }
    public Veiculo(int veiculoCodigo, Condutor condutor, Modelo modelo, String veiculoStatus, String veiculoPlaca, String veiculoCor, Integer veiculoAno, Set tags) {
       this.veiculoCodigo = veiculoCodigo;
       this.condutor = condutor;
       this.modelo = modelo;
       this.veiculoStatus = veiculoStatus;
       this.veiculoPlaca = veiculoPlaca;
       this.veiculoCor = veiculoCor;
       this.veiculoAno = veiculoAno;
       this.tags = tags;
    }
   
    public int getVeiculoCodigo() {
        return this.veiculoCodigo;
    }
    
    public void setVeiculoCodigo(int veiculoCodigo) {
        this.veiculoCodigo = veiculoCodigo;
    }
    public Condutor getCondutor() {
        return this.condutor;
    }
    
    public void setCondutor(Condutor condutor) {
        this.condutor = condutor;
    }
    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }
    public String getVeiculoStatus() {
        return this.veiculoStatus;
    }
    
    public void setVeiculoStatus(String veiculoStatus) {
        this.veiculoStatus = veiculoStatus;
    }
    public String getVeiculoPlaca() {
        return this.veiculoPlaca;
    }
    
    public void setVeiculoPlaca(String veiculoPlaca) {
        this.veiculoPlaca = veiculoPlaca;
    }
    public String getVeiculoCor() {
        return this.veiculoCor;
    }
    
    public void setVeiculoCor(String veiculoCor) {
        this.veiculoCor = veiculoCor;
    }
    public Integer getVeiculoAno() {
        return this.veiculoAno;
    }
    
    public void setVeiculoAno(Integer veiculoAno) {
        this.veiculoAno = veiculoAno;
    }
    public Set getTags() {
        return this.tags;
    }
    
    public void setTags(Set tags) {
        this.tags = tags;
    }




}


